import { worldGraphLegacyRecipes } from "./world-graph-3.mjs";
import { GRAPH_BREADTH_RECIPES } from "./graph-breadth-recipes.mjs";

const tuple = (a, b, word, emoji, note) => Object.freeze({ a, b, word, emoji, note, source: "expanded" });

export const EXPANDED_RECIPE_BASE_CONCEPTS = Object.freeze([
  "Air", "Alloy", "Animal", "Aquarium", "Ash", "Astronomy", "Atmosphere", "Atlas", "Axe", "Balloon", "Barbecue",
  "Beach", "Binary Star", "Bird", "Blizzard", "Bouquet", "Brick", "Canal", "City", "Clay", "Cloud", "Color",
  "Comet", "Concrete", "Confluence", "Constellation", "Dam", "Day", "Daylight", "Desert", "Dinner", "Dragon", "Dragon Brood",
  "Dragon Lair", "Dune", "Dust", "Dust Storm", "Earth", "Ecosystem", "Electric Shock", "Electricity", "Energy",
  "Drone", "Engine", "Evaporation", "Excavator", "Extinction", "Factory", "Farm", "Field", "Fire", "Fire Dragon", "Fireplace",
  "Firestorm", "Firewall", "Fireweed", "Fish", "Fleet", "Flock", "Flood", "Flower", "Flying Dragon", "Flying Fish",
  "Fog", "Forest", "Fortress", "Fossil", "Galaxy", "Garden", "Geyser", "Glacier", "Glass", "Grounding", "High Voltage",
  "Forge Bot", "Hardware", "Home", "Horizon", "House", "Houseboat", "Hurricane", "Hydrogen", "Ice", "Iceberg", "Inferno", "Jet", "Jungle",
  "Kiln", "Land", "Laser", "Lava", "Leaf", "Lens", "Life", "Light", "Lightning", "Machine", "Marsh", "Megacity",
  "Airship", "Ashes", "Metal", "Meteor", "Mirror", "Mist", "Mountain", "Mud", "Observatory", "Obsidian", "Ocean", "Ocean World", "Open Book", "Ore",
  "Park", "Pebble", "Phoenix", "Plane", "Planet", "Plant", "Plasma", "Pollen", "Pond", "Port", "Pottery",
  "Power", "Prism", "Quagmire", "Rain", "Rainbow", "Rainforest", "Range", "Reflection", "River", "Rocket", "Root", "Rover", "Ruins", "Rust",
  "Sand", "School", "Sculpture", "Sea Dragon", "Seed", "Shadow", "Shelter", "Sky", "Smog", "Smoke", "Snow", "Solar Flare",
  "Solar System", "Space", "Space Station", "Spacecraft", "Species", "Spectrum", "Star", "Starfish", "Steam", "Steel", "Stone",
  "Storm", "Sun", "Superstorm", "Swamp", "Telescope", "Tornado", "Tree", "Universe", "Vacuum", "Valley", "Vase", "Village",
  "Volcanic Planet", "Volcano", "Wall", "Water", "Water Lily", "Weather", "Wildfire", "Wildlife", "Wind", "Window", "Wireless", "Wonder", "World"
]);

// This catalog is intentionally ordered. Every ingredient is either part of
// the authored base universe above or is introduced by an earlier recipe.
// That makes the whole expansion progressively reachable without a semantic
// category roulette or invented portmanteau fallback.
export const EXPANDED_RECIPES = Object.freeze([
  // Weather, landscapes, and water.
  tuple("Rain", "Sun", "Sunshower", "🌦️", "Rain falling in sunshine is a sunshower."),
  tuple("Rain", "Wind", "Squall", "🌬️", "Wind driving sudden rain becomes a squall."),
  tuple("Fog", "Light", "Halo", "⭕", "Light scattered through fog forms a halo."),
  tuple("Fog", "Sun", "Fogbow", "🌫️", "Sunlight refracting through fog forms a fogbow."),
  tuple("Snow", "Sun", "Meltwater", "💧", "Sun-warmed snow drains away as meltwater."),
  tuple("Snow", "Wind", "Snowdrift", "❄️", "Wind piles loose snow into a drift."),
  tuple("Ice", "Wind", "Wind Chill", "🥶", "Wind over ice makes the cold feel sharper."),
  tuple("Ice", "Sun", "Thaw", "💧", "Sunlight warming ice begins a thaw."),
  tuple("River", "Ocean", "Estuary", "🌊", "A river meeting the ocean forms an estuary."),
  tuple("River", "Valley", "Watershed", "🏞️", "A river and its valley define a watershed."),
  tuple("River", "Desert", "Oasis", "🌴", "A desert river sustains an oasis."),
  tuple("River", "City", "Waterfront", "🌆", "A city beside a river develops a waterfront."),
  tuple("Mountain", "River", "Waterfall", "💦", "A river dropping from a mountain becomes a waterfall."),
  tuple("Mountain", "Forest", "Highlands", "🏔️", "Forested mountains form green highlands."),
  tuple("Mountain", "Desert", "Mesa", "🏜️", "Erosion leaves a flat-topped desert mesa."),
  tuple("Mountain", "Ice", "Ice Cap", "🧊", "Persistent mountain ice forms an ice cap."),
  tuple("Mountain", "Wind", "Updraft", "💨", "Wind climbing a mountain becomes an updraft."),
  tuple("Ocean", "Wind", "Wave", "🌊", "Wind transfers its motion into ocean waves."),
  tuple("Ocean", "Storm", "Tempest", "⛈️", "A storm raging over the ocean becomes a tempest."),
  tuple("Ocean", "Beach", "Coast", "🏖️", "Ocean and beach together define a coast."),
  tuple("Ocean", "Ice", "Pack Ice", "🧊", "Sea ice pressed together becomes pack ice."),
  tuple("Ocean", "Volcano", "Island", "🏝️", "A volcano rising from the ocean builds an island."),
  tuple("Ocean", "Earth", "Continent", "🌍", "Great masses of earth divide the ocean into continents."),
  tuple("Desert", "Wind", "Sandstorm", "🌪️", "Strong desert wind raises a sandstorm."),
  tuple("Desert", "Rain", "Flash Flood", "🌊", "Sudden desert rain can cause a flash flood."),
  tuple("Desert", "Plant", "Cactus", "🌵", "A plant adapted to desert drought becomes a cactus."),
  tuple("Desert", "Animal", "Camel", "🐪", "An animal adapted to desert travel becomes a camel."),
  tuple("Forest", "Wind", "Rustle", "🍃", "Wind moving through a forest creates a rustle."),
  tuple("Forest", "Fog", "Cloud Forest", "🌲", "Persistent fog turns a high forest into a cloud forest."),
  tuple("Forest", "River", "Woodland Stream", "🏞️", "A small river through forest becomes a woodland stream."),
  tuple("Forest", "Range", "Montane Forest", "🌲", "A forest spread across a mountain range becomes montane forest."),
  tuple("Forest", "Animal", "Fauna", "🦌", "Animals living throughout a forest are its fauna."),
  tuple("Forest", "Flower", "Wildflower", "🌼", "An untended forest flower becomes a wildflower."),
  tuple("Jungle", "Animal", "Tiger", "🐅", "A great jungle predator is a tiger."),
  tuple("Jungle", "Bird", "Parrot", "🦜", "A colorful bird of the jungle is a parrot."),
  tuple("Swamp", "Light", "Will-o'-the-wisp", "✨", "A strange swamp light evokes a will-o'-the-wisp."),
  tuple("Swamp", "Tree", "Mangrove", "🌳", "A tree adapted to tidal swamp becomes a mangrove."),
  tuple("Marsh", "Bird", "Heron", "🐦", "A long-legged marsh bird is a heron."),
  tuple("Marsh", "Water", "Wetland", "🪷", "Waterlogged marsh ground forms a wetland."),
  tuple("Pond", "Fish", "Koi Pond", "🐟", "A pond stocked with ornamental fish becomes a koi pond."),
  tuple("Pond", "Flower", "Lily Pond", "🪷", "Water flowers turn a pond into a lily pond."),
  tuple("Beach", "Wind", "Sea Breeze", "🌬️", "Air moving inland from a beach is a sea breeze."),
  tuple("Beach", "Glass", "Sea Glass", "💎", "Surf tumbles glass into smooth sea glass."),
  tuple("Beach", "Fire", "Bonfire", "🔥", "A large fire on a beach becomes a bonfire."),
  tuple("Beach", "House", "Beach House", "🏠", "A house built by the beach is a beach house."),
  tuple("Dune", "Plant", "Dune Grass", "🌾", "Deep-rooted grass stabilizes a sand dune."),
  tuple("Valley", "Fog", "Inversion", "🌫️", "Cool fog trapped in a valley marks an inversion."),
  tuple("Valley", "Village", "Hamlet", "🏘️", "A tiny village nestled in a valley is a hamlet."),
  tuple("Valley", "Flood", "Floodplain", "🏞️", "Floodwater spreading through a valley creates a floodplain."),
  tuple("River", "Stone", "Canyon", "🏜️", "A river cutting stone over time forms a canyon."),
  tuple("Glacier", "Mountain", "Icefall", "🧊", "A steep mountain glacier breaks into an icefall."),
  tuple("Glacier", "Ocean", "Ice Shelf", "🧊", "A glacier extending over the ocean forms an ice shelf."),
  tuple("Glacier", "River", "Glacial Lake", "🏔️", "Glacial melt feeding a basin creates a glacial lake."),
  tuple("Volcano", "Island", "Caldera", "🌋", "A collapsed island volcano can leave a vast caldera."),
  tuple("Volcano", "Ash", "Tuff", "🪨", "Compacted volcanic ash becomes tuff."),
  tuple("Volcano", "Smoke", "Eruption", "🌋", "A smoking volcano signals an eruption."),
  tuple("Lava", "Ocean", "Pillow Lava", "🌋", "Lava cooling underwater forms pillow lava."),
  tuple("Stone", "Wind", "Ventifact", "🪨", "Wind-blown sand sculpts stone into a ventifact."),
  tuple("Stone", "Forest", "Moss", "🌿", "Damp forest stone becomes covered in moss."),
  tuple("Stone", "Rain", "Weathering", "🪨", "Rain slowly weathers exposed stone."),
  tuple("Pebble", "Ocean", "Shingle", "🏖️", "Ocean-rounded pebbles gather into shingle."),
  tuple("Sand", "Plant", "Marram Grass", "🌾", "A hardy plant binding sand becomes marram grass."),
  tuple("Clay", "River", "Silt", "🟤", "Fine clay carried by a river settles as silt."),
  tuple("Mud", "River", "Delta", "🔺", "River mud deposited at its mouth builds a delta."),
  tuple("Mud", "Animal", "Footprint", "🐾", "An animal stepping in mud leaves a footprint."),
  tuple("Dust", "Wind", "Dust Devil", "🌪️", "Spinning wind lifts dust into a dust devil."),
  tuple("Dust", "Light", "Sunbeam", "☀️", "Dust reveals a shaft of light as a sunbeam."),
  tuple("Smoke", "Fog", "Haze", "🌫️", "Smoke mixed with fog produces a heavy haze."),
  tuple("Cloud", "Sun", "Silver Lining", "☀️", "Sun behind a cloud reveals a silver lining."),
  tuple("Cloud", "Wind", "Cloudbank", "☁️", "Wind gathers clouds into a cloudbank."),
  tuple("Storm", "Mountain", "Orographic Rain", "🌧️", "A mountain forces storm air upward into rain."),
  tuple("Storm", "City", "Blackout", "🌃", "A severe city storm can cause a blackout."),
  tuple("Lightning", "Tree", "Splinter", "🪵", "Lightning striking a tree blasts out splinters."),
  tuple("Lightning", "Cloud", "Thunderhead", "⛈️", "A charged storm cloud becomes a thunderhead."),
  tuple("Rainbow", "Fog", "Glory", "🌈", "Sunlight in mist can form a circular glory."),
  tuple("Rainbow", "Water", "Refraction", "🌈", "Water droplets split light through refraction."),
  tuple("Atmosphere", "Sun", "Blue Sky", "🌤️", "The atmosphere scatters sunlight into a blue sky."),
  tuple("Atmosphere", "Planet", "Climate", "🌍", "A planet's atmosphere shapes its climate."),

  // Living systems, farms, and food.
  tuple("Plant", "Sun", "Photosynthesis", "🌿", "Plants use sunlight for photosynthesis."),
  tuple("Plant", "Rain", "Growth", "🌱", "Rain nourishes a plant's growth."),
  tuple("Plant", "Wind", "Pollination", "🐝", "Wind carries pollen between plants."),
  tuple("Plant", "Stone", "Lichen", "🌿", "A hardy plantlike growth on stone evokes lichen."),
  tuple("Tree", "Sun", "Shade", "🌳", "A tree blocking sunlight provides shade."),
  tuple("Tree", "River", "Driftwood", "🪵", "A river carries fallen tree wood as driftwood."),
  tuple("Tree", "Stone", "Petrified Wood", "🪨", "Minerals replacing buried wood create petrified wood."),
  tuple("Tree", "Ash", "Charcoal", "⚫", "A partly burned tree can leave charcoal among its ash."),
  tuple("Tree", "House", "Lumber", "🪵", "Timber prepared for building a house becomes lumber."),
  tuple("Axe", "Tree", "Log", "🪵", "An axe fells a tree into a log."),
  tuple("Log", "Fire", "Campfire", "🔥", "Logs arranged and lit become a campfire."),
  tuple("Log", "Water", "Raft", "🛶", "Logs bound to float on water form a raft."),
  tuple("Log", "House", "Cabin", "🛖", "A house built from logs becomes a cabin."),
  tuple("Seed", "Sun", "Sprout", "🌱", "A seed warmed by sunlight begins to sprout."),
  tuple("Seed", "Rain", "Seedling", "🌱", "Rain helps a seed grow into a seedling."),
  tuple("Seed", "Wind", "Dandelion", "🌼", "A wind-carried seed evokes a dandelion."),
  tuple("Seed", "Field", "Crop", "🌾", "Seeds planted across a field become a crop."),
  tuple("Root", "Water", "Absorption", "💧", "Roots take in water through absorption."),
  tuple("Root", "Stone", "Crack", "🪨", "A growing root can split stone along a crack."),
  tuple("Root", "Forest", "Root Network", "🌳", "Connected forest roots form an underground network."),
  tuple("Leaf", "Sun", "Chlorophyll", "🍃", "Chlorophyll lets a leaf capture sunlight."),
  tuple("Leaf", "Wind", "Flutter", "🍃", "A leaf moving in wind begins to flutter."),
  tuple("Leaf", "Water", "Dew", "💧", "Water beading on a leaf becomes dew."),
  tuple("Leaf", "Fire", "Ember", "🔥", "A burning leaf curls into a glowing ember."),
  tuple("Flower", "Sun", "Sunflower", "🌻", "A flower turning toward the sun evokes a sunflower."),
  tuple("Flower", "Wind", "Scent", "🌸", "Wind carries a flower's scent."),
  tuple("Flower", "Garden", "Flowerbed", "🌷", "Flowers arranged in a garden form a flowerbed."),
  tuple("Flower", "Rain", "Blossom", "🌸", "Rain helps a flower open into blossom."),
  tuple("Pollen", "Wind", "Hay Fever", "🤧", "Windborne pollen can trigger hay fever."),
  tuple("Pollen", "Flower", "Nectar", "🍯", "A pollinated flower offers nectar."),
  tuple("Farm", "Water", "Irrigation", "💧", "Water directed across a farm provides irrigation."),
  tuple("Farm", "Machine", "Tractor", "🚜", "A farm machine built for fieldwork is a tractor."),
  tuple("Farm", "Animal", "Livestock", "🐄", "Animals raised on a farm are livestock."),
  tuple("Farm", "Plant", "Agriculture", "🌾", "Growing plants on farms is agriculture."),
  tuple("Farm", "House", "Barn", "🏚️", "A farm building for crops and animals is a barn."),
  tuple("Field", "Animal", "Pasture", "🐄", "A field where animals graze becomes pasture."),
  tuple("Field", "Flower", "Meadow", "🌼", "A field filled with flowers becomes a meadow."),
  tuple("Field", "Water", "Paddy", "🌾", "A flooded field for growing rice is a paddy."),
  tuple("Field", "Wind", "Wind Farm", "🌬️", "A windy field filled with turbines is a wind farm."),
  tuple("Garden", "Bird", "Birdbath", "🐦", "A garden water basin for birds is a birdbath."),
  tuple("Garden", "Wall", "Walled Garden", "🌿", "A garden enclosed by walls becomes a walled garden."),
  tuple("Garden", "House", "Greenhouse", "🏡", "A glass garden house becomes a greenhouse."),
  tuple("Garden", "Stone", "Rock Garden", "🪨", "A garden arranged around stones is a rock garden."),
  tuple("Forest", "Wildlife", "Habitat", "🦌", "A forest supporting wildlife is a habitat."),
  tuple("Ecosystem", "Species", "Biodiversity", "🦋", "Many species in one ecosystem create biodiversity."),
  tuple("Ecosystem", "Water", "Ecology", "🌿", "Water links organisms through an ecosystem's ecology."),
  tuple("Ecosystem", "City", "Urban Ecology", "🏙️", "Ecology within a city becomes urban ecology."),
  tuple("Wildlife", "City", "Urban Wildlife", "🦊", "Wild animals adapting to cities become urban wildlife."),
  tuple("Wildlife", "Water", "Otter", "🦦", "Water-loving wildlife evokes an otter."),
  tuple("Animal", "House", "Pet", "🐾", "An animal sharing a house becomes a pet."),
  tuple("Animal", "Range", "Mountain Lion", "🐆", "A large animal roaming a mountain range evokes a mountain lion."),
  tuple("Animal", "Mountain", "Goat", "🐐", "An animal sure-footed on mountains is a goat."),
  tuple("Animal", "Ice", "Polar Bear", "🐻‍❄️", "A large animal adapted to Arctic ice is a polar bear."),
  tuple("Animal", "Ocean", "Whale", "🐋", "A great animal living in the ocean is a whale."),
  tuple("Animal", "Village", "Livestock", "🐄", "Animals raised around a village become livestock."),
  tuple("Bird", "Water", "Duck", "🦆", "A bird adapted to ponds and water is a duck."),
  tuple("Bird", "Ocean", "Seabird", "🐦", "A bird living over the ocean is a seabird."),
  tuple("Bird", "Tree", "Nest", "🪺", "A bird building in a tree makes a nest."),
  tuple("Bird", "City", "Pigeon", "🐦", "A familiar city bird is a pigeon."),
  tuple("Bird", "Flower", "Hummingbird", "🐦", "A flower-feeding bird evokes a hummingbird."),
  tuple("Fish", "River", "Trout", "🐟", "A familiar river fish is a trout."),
  tuple("Fish", "Ocean", "Tuna", "🐟", "A fast ocean fish is a tuna."),
  tuple("Fish", "Ice", "Arctic Char", "🐟", "A fish adapted to icy water is Arctic char."),
  tuple("Fish", "Bird", "Penguin", "🐧", "A fish-eating seabird is a penguin."),
  tuple("Fish", "Glass", "Fishbowl", "🐠", "Glass holding a pet fish forms a fishbowl."),
  tuple("Fish", "Garden", "Koi", "🐟", "An ornamental garden fish is a koi."),
  tuple("Species", "Forest", "Biodiversity", "🦋", "Many forest species create biodiversity."),
  tuple("Species", "City", "Population", "👥", "A species living together in a city forms a population."),
  tuple("Life", "Ocean", "Plankton", "🦠", "Tiny life drifting in the ocean is plankton."),
  tuple("Life", "Sun", "Vitality", "💚", "Sunlight supports life's vitality."),
  tuple("Life", "Ice", "Hibernation", "😴", "Life enduring deep cold may enter hibernation."),
  tuple("Life", "Fire", "Survival", "🛡️", "Life enduring fire demonstrates survival."),
  tuple("Fossil", "Stone", "Fossil Record", "🦴", "Fossils preserved in stone form the fossil record."),
  tuple("Fossil", "Fire", "Fossil Fuel", "🛢️", "Ancient organic matter burned for energy is fossil fuel."),
  tuple("Fossil", "Plant", "Coal", "⚫", "Ancient compressed plant fossils become coal."),
  tuple("Ocean", "Plant", "Seaweed", "🌿", "A plantlike organism growing in the ocean is seaweed."),
  tuple("Ocean", "Flower", "Anemone", "🪸", "A flower-shaped ocean animal is an anemone."),
  tuple("Water Lily", "Pond", "Lotus", "🪷", "A stately pond flower evokes a lotus."),
  tuple("Rainforest", "Animal", "Monkey", "🐒", "A familiar rainforest animal is a monkey."),
  tuple("Rainforest", "Bird", "Toucan", "🦜", "A bright rainforest bird is a toucan."),
  tuple("Plant", "Dinner", "Salad", "🥗", "Fresh edible plants served at dinner make a salad."),
  tuple("Fish", "Dinner", "Seafood", "🍽️", "Fish prepared for dinner becomes seafood."),
  tuple("Ocean", "Dinner", "Sushi", "🍣", "Ocean fish prepared for a meal evokes sushi."),
  tuple("Garden", "Dinner", "Vegetables", "🥕", "A kitchen garden supplies vegetables for dinner."),
  tuple("Field", "Dinner", "Picnic", "🧺", "Dinner eaten in a field becomes a picnic."),
  tuple("Bird", "Dinner", "Poultry", "🍗", "Farmed birds prepared as food are poultry."),
  tuple("Animal", "Dinner", "Meat", "🥩", "Animal food served at dinner becomes meat."),
  tuple("Flower", "Dinner", "Garnish", "🌿", "An edible flower can become a dinner garnish."),
  tuple("Seed", "Dinner", "Grain", "🌾", "Edible seeds gathered for meals become grain."),
  tuple("Grain", "Water", "Porridge", "🥣", "Grain simmered in water becomes porridge."),
  tuple("Grain", "Fire", "Bread", "🍞", "Heat transforms prepared grain into bread."),
  tuple("Bread", "Fire", "Toast", "🍞", "Bread browned by fire becomes toast."),
  tuple("Grain", "Stone", "Millstone", "🪨", "Stone used to grind grain becomes a millstone."),
  tuple("Farm", "Grain", "Harvest", "🌾", "Gathering ripe farm grain creates a harvest."),
  tuple("Harvest", "Dinner", "Feast", "🍽️", "A plentiful harvest supports a feast."),
  tuple("Tree", "Flower", "Fruit", "🍎", "A pollinated tree flower grows into fruit."),
  tuple("Fruit", "Water", "Juice", "🧃", "Pressed fruit mixed with water becomes juice."),
  tuple("Fruit", "Fire", "Jam", "🍓", "Fruit cooked with heat becomes jam."),
  tuple("Fruit", "Ice", "Sorbet", "🍧", "Frozen fruit becomes sorbet."),
  tuple("Fruit", "Dinner", "Dessert", "🍰", "Sweet fruit after dinner becomes dessert."),
  tuple("Flower", "Animal", "Bee", "🐝", "An animal visiting flowers for nectar is a bee."),
  tuple("Bee", "Flower", "Honey", "🍯", "Bees turn flower nectar into honey."),
  tuple("Honey", "Fire", "Caramel", "🍬", "Heating honey creates a caramel-like sweet."),
  tuple("Honey", "Water", "Sweet Tea", "🫖", "Honey dissolved in brewed water makes sweet tea."),
  tuple("Leaf", "Steam", "Tea", "🫖", "Steaming leaves produces tea."),
  tuple("Tea", "Ice", "Iced Tea", "🧊", "Chilled tea served over ice becomes iced tea."),
  tuple("Fish", "Smoke", "Smoked Fish", "🐟", "Smoke preserves fish as smoked fish."),

  // Homes, cities, making, and transport.
  tuple("Clay", "House", "Adobe", "🧱", "Sun-dried clay used for a house becomes adobe."),
  tuple("Clay", "Wall", "Plaster", "🏠", "Smooth clay spread over a wall becomes plaster."),
  tuple("Brick", "Stone", "Masonry", "🧱", "Brick and stone construction is masonry."),
  tuple("Brick", "Metal", "Construction", "🏗️", "Brick supported by metal becomes modern construction."),
  tuple("Brick", "Glass", "Facade", "🏢", "Brick and glass shape a building facade."),
  tuple("Brick", "House", "Chimney", "🏠", "A brick shaft on a house becomes a chimney."),
  tuple("Stone", "City", "Cobblestone", "🪨", "Shaped stone paving a city becomes cobblestone."),
  tuple("Stone", "House", "Cottage", "🏡", "A small stone house becomes a cottage."),
  tuple("Stone", "Wall", "Rampart", "🏰", "A massive stone wall becomes a rampart."),
  tuple("Stone", "Glass", "Mosaic", "🖼️", "Stone and glass pieces arranged together form a mosaic."),
  tuple("Wall", "Water", "Levee", "🌊", "A wall holding back water becomes a levee."),
  tuple("Wall", "City", "Citadel", "🏰", "Defensive walls protecting a city form a citadel."),
  tuple("Wall", "Park", "Terrace", "🌿", "A retaining wall shapes a park terrace."),
  tuple("Wall", "Glass", "Window", "🪟", "Glass fitted into a wall creates a window."),
  tuple("House", "Wind", "Windmill", "🌬️", "A building harnessing wind becomes a windmill."),
  tuple("House", "Forest", "Treehouse", "🏡", "A house built among trees becomes a treehouse."),
  tuple("House", "City", "Apartment", "🏢", "A city dwelling within a larger building is an apartment."),
  tuple("House", "Snow", "Igloo", "🧊", "A snow-built shelter becomes an igloo."),
  tuple("House", "Ice", "Icehouse", "🧊", "An insulated house for storing ice is an icehouse."),
  tuple("House", "Field", "Farmhouse", "🏡", "A house serving surrounding fields is a farmhouse."),
  tuple("Home", "City", "Neighborhood", "🏘️", "Homes grouped within a city form a neighborhood."),
  tuple("Home", "Water", "Plumbing", "🚰", "Water routed through a home becomes plumbing."),
  tuple("Home", "Energy", "Utility", "🔌", "Energy supplied to a home is a utility."),
  tuple("Shelter", "Animal", "Kennel", "🐕", "A shelter built for a dog is a kennel."),
  tuple("Shelter", "Forest", "Hut", "🛖", "A simple forest shelter becomes a hut."),
  tuple("Shelter", "Mountain", "Lodge", "🏔️", "A mountain shelter for travelers becomes a lodge."),
  tuple("Village", "River", "Riverside", "🏞️", "A village beside a river develops a riverside."),
  tuple("Village", "Forest", "Settlement", "🏘️", "A village established in forest is a settlement."),
  tuple("Village", "Mountain", "Hill Town", "🏘️", "A mountain village becomes a hill town."),
  tuple("Megacity", "River", "Bridge", "🌉", "A megacity crossing a river depends on major bridges."),
  tuple("City", "Ocean", "Harbor", "⚓", "A protected city waterfront becomes a harbor."),
  tuple("City", "Forest", "Greenbelt", "🌳", "Protected forest around a city forms a greenbelt."),
  tuple("City", "Garden", "Public Park", "🏞️", "A large civic garden becomes a public park."),
  tuple("City", "Energy", "Power Grid", "⚡", "Energy distributed across a city forms a power grid."),
  tuple("City", "Machine", "Industry", "🏭", "Machines working across a city create industry."),
  tuple("City", "Smoke", "Pollution", "🏭", "Smoke accumulating over a city becomes pollution."),
  tuple("City", "Light", "Streetlight", "💡", "A city light mounted along a road is a streetlight."),
  tuple("Land", "City", "Road", "🛣️", "A prepared route across land into a city is a road."),
  tuple("Road", "City", "Street", "🛣️", "A road within a city becomes a street."),
  tuple("Road", "Village", "Main Street", "🏘️", "A village's central road becomes its main street."),
  tuple("Road", "Mountain", "Pass", "🏔️", "A road crossing mountains follows a pass."),
  tuple("Road", "River", "Bridge", "🌉", "A road crossing a river requires a bridge."),
  tuple("Road", "Forest", "Trail", "🥾", "A narrow road through forest becomes a trail."),
  tuple("Road", "Machine", "Vehicle", "🚗", "A machine made to travel roads is a vehicle."),
  tuple("Vehicle", "Energy", "Electric Vehicle", "🚙", "A vehicle driven by stored energy is electric."),
  tuple("Vehicle", "Road", "Traffic", "🚦", "Vehicles sharing a road create traffic."),
  tuple("Vehicle", "Metal", "Car", "🚗", "A metal road vehicle becomes a car."),
  tuple("Vehicle", "Ocean", "Ship", "🚢", "A large vehicle made to cross the ocean is a ship."),
  tuple("Raft", "Metal", "Boat", "⛵", "Adding a shaped metal hull turns a simple raft into a boat."),
  tuple("Vehicle", "Sky", "Aircraft", "✈️", "A vehicle made to travel through the sky is an aircraft."),
  tuple("Metal", "Road", "Railway", "🛤️", "Metal rails laid along a route form a railway."),
  tuple("Railway", "Machine", "Train", "🚆", "A machine built to travel a railway is a train."),
  tuple("Train", "City", "Subway", "🚇", "An urban train running below streets is a subway."),
  tuple("Train", "Mountain", "Tunnel", "🚇", "A train crossing a mountain uses a tunnel."),
  tuple("Train", "Water", "Bridge", "🌉", "A train crossing water needs a bridge."),
  tuple("Train", "Steam", "Steam Train", "🚂", "Steam driving a train creates a steam train."),
  tuple("Train", "Electricity", "Electric Train", "🚆", "Electricity powering a train creates an electric train."),
  tuple("Port", "Train", "Freight", "📦", "Trains carrying goods from a port move freight."),
  tuple("Port", "City", "Trade", "⚓", "A city port supports trade."),
  tuple("Port", "Ocean", "Seaport", "⚓", "A port opening onto the ocean is a seaport."),
  tuple("Canal", "City", "Waterway", "🚤", "A canal through a city is an urban waterway."),
  tuple("Canal", "Boat", "Barge", "🚢", "A broad cargo boat on a canal is a barge."),
  tuple("Dam", "Energy", "Hydropower", "⚡", "A dam converting moving water produces hydropower."),
  tuple("Dam", "River", "Reservoir", "🌊", "A dam holding a river creates a reservoir."),
  tuple("Reservoir", "City", "Water Supply", "🚰", "A reservoir serving a city provides its water supply."),
  tuple("Reservoir", "Fish", "Fishery", "🐟", "A managed reservoir stocked with fish becomes a fishery."),
  tuple("Fortress", "City", "Capital", "🏛️", "A fortified city can become a capital."),
  tuple("Fortress", "Mountain", "Stronghold", "🏰", "A mountain fortress becomes a stronghold."),
  tuple("Fortress", "Wall", "Battlement", "🏰", "A defensive wall atop a fortress forms a battlement."),
  tuple("Fortress", "Bridge", "Drawbridge", "🌉", "A movable fortress bridge becomes a drawbridge."),
  tuple("Glass", "House", "Skylight", "🪟", "Glass fitted into a roof becomes a skylight."),
  tuple("Glass", "City", "Skyscraper", "🏙️", "Glass towers in a city form a skyscraper."),
  tuple("Glass", "Steel", "Curtain Wall", "🏙️", "Glass hung from a steel frame forms a curtain wall."),
  tuple("Glass", "Garden", "Greenhouse", "🏡", "Glass enclosing a garden forms a greenhouse."),
  tuple("Metal", "House", "Framework", "🏗️", "Metal supporting a house forms its framework."),
  tuple("Metal", "Wall", "Gate", "🚪", "A movable metal section in a wall becomes a gate."),
  tuple("Metal", "Glass", "Mirror", "🪞", "A metal backing turns polished glass into a mirror."),
  tuple("Steel", "City", "Skyscraper", "🏙️", "Steel framing lets a city build skyscrapers."),
  tuple("Steel", "Bridge", "Suspension Bridge", "🌉", "Steel cables supporting a bridge create a suspension bridge."),
  tuple("Steel", "Machine", "Robot", "🤖", "A steel machine designed to act becomes a robot."),
  tuple("Robot", "Factory", "Automation", "🏭", "Robots coordinating in a factory create automation."),
  tuple("Robot", "House", "Smart Home", "🏠", "Household robots and controls create a smart home."),
  tuple("Machine", "House", "Appliance", "🔌", "A machine designed for household work is an appliance."),
  tuple("Machine", "Water", "Pump", "⚙️", "A machine moving water is a pump."),
  tuple("Machine", "Wind", "Turbine", "🌬️", "A machine extracting power from wind is a turbine."),
  tuple("Factory", "City", "Industrial Park", "🏭", "Factories grouped in a city form an industrial park."),
  tuple("Factory", "Smoke", "Emissions", "🏭", "Smoke released by a factory becomes emissions."),
  tuple("Factory", "Water", "Wastewater", "💧", "Used factory water becomes wastewater."),
  tuple("Factory", "Energy", "Manufacturing", "🏭", "A powered factory carries out manufacturing."),
  tuple("Excavator", "Stone", "Quarry", "⛏️", "An excavator cutting stone works a quarry."),
  tuple("Excavator", "Road", "Roadworks", "🚧", "An excavator rebuilding a road creates roadworks."),
  tuple("Axe", "Log", "Firewood", "🪵", "An axe splitting logs produces firewood."),
  tuple("Axe", "Forest", "Logging", "🪓", "Using axes across a forest becomes logging."),
  tuple("Lumber", "House", "Furniture", "🪑", "Shaped lumber furnishing a house becomes furniture."),
  tuple("Lumber", "Water", "Paper Pulp", "📄", "Lumber broken down with water becomes paper pulp."),
  tuple("Paper Pulp", "Fire", "Paper", "📄", "Heat dries pressed pulp into paper."),
  tuple("Paper", "School", "Notebook", "📓", "Bound paper used at school becomes a notebook."),
  tuple("Paper", "Light", "Lantern", "🏮", "Paper surrounding a safe light becomes a lantern."),
  tuple("Paper", "Wind", "Kite", "🪁", "Paper shaped to catch wind becomes a kite."),
  tuple("Pottery", "Fire", "Ceramic", "🏺", "Repeated firing turns pottery into durable ceramic."),
  tuple("Pottery", "Plant", "Flowerpot", "🪴", "Pottery made to hold a plant becomes a flowerpot."),
  tuple("Pottery", "Dinner", "Plate", "🍽️", "Flat pottery used at dinner becomes a plate."),
  tuple("Vase", "Flower", "Bouquet", "💐", "Flowers arranged in a vase form a bouquet."),
  tuple("Sculpture", "City", "Monument", "🗿", "A civic sculpture becomes a monument."),
  tuple("Sculpture", "Garden", "Statue", "🗿", "A sculpture displayed in a garden becomes a statue."),
  tuple("Mirror", "House", "Dressing Room", "🪞", "A room arranged around mirrors becomes a dressing room."),
  tuple("Mirror", "Light", "Reflection", "🪞", "A mirror returns light as a reflection."),
  tuple("Window", "Rain", "Rain Streaks", "🌧️", "Rain running down a window leaves streaks."),
  tuple("Window", "Sun", "Sunlight", "☀️", "Sun shining through a window fills a room with sunlight."),
  tuple("Window", "House", "Room", "🚪", "Windows and walls enclose a habitable room."),

  // Energy, machines, space, science, and knowledge.
  tuple("Electricity", "House", "Wiring", "🔌", "Electricity routed through a house uses wiring."),
  tuple("Electricity", "City", "Electrical Grid", "⚡", "Citywide electrical connections form a grid."),
  tuple("Electricity", "Metal", "Circuit", "🔌", "Metal paths carrying electricity form a circuit."),
  tuple("Electricity", "Glass", "Light Bulb", "💡", "Electricity glowing inside glass creates a light bulb."),
  tuple("Electricity", "Wind", "Wind Power", "🌬️", "Wind converted into electricity becomes wind power."),
  tuple("Electricity", "Sun", "Solar Power", "☀️", "Sunlight converted into electricity becomes solar power."),
  tuple("Energy", "Sun", "Solar Energy", "☀️", "Energy arriving from the sun is solar energy."),
  tuple("Energy", "Wind", "Wind Energy", "🌬️", "Energy captured from wind is wind energy."),
  tuple("Energy", "River", "Hydro Energy", "🌊", "A river's motion can provide hydro energy."),
  tuple("Energy", "Ocean", "Tidal Power", "🌊", "Ocean tides converted into energy create tidal power."),
  tuple("Energy", "Plant", "Biofuel", "🌿", "Plant matter converted into energy becomes biofuel."),
  tuple("Power", "City", "Power Plant", "🏭", "A facility supplying power to a city is a power plant."),
  tuple("Power", "House", "Outlet", "🔌", "Household power reaches devices through an outlet."),
  tuple("Power", "Machine", "Motor", "⚙️", "Power converted into machine motion drives a motor."),
  tuple("Power", "Water", "Hydroelectricity", "⚡", "Power generated from moving water is hydroelectricity."),
  tuple("Power", "Wind", "Generator", "⚙️", "Wind turning a generator produces power."),
  tuple("Engine", "Car", "Automobile", "🚗", "An engine driving a road car creates an automobile."),
  tuple("Engine", "Boat", "Motorboat", "🚤", "An engine driving a boat creates a motorboat."),
  tuple("Engine", "Plane", "Airliner", "✈️", "A large engine-powered passenger plane is an airliner."),
  tuple("Engine", "Train", "Locomotive", "🚂", "An engine pulling a train is a locomotive."),
  tuple("Engine", "Farm", "Tractor", "🚜", "A farm vehicle built around an engine is a tractor."),
  tuple("Engine", "Fire", "Combustion", "🔥", "Fire inside an engine is combustion."),
  tuple("Engine", "Steam", "Steam Engine", "🚂", "Steam driving an engine creates a steam engine."),
  tuple("Plane", "City", "Airport", "🛫", "A city serving planes builds an airport."),
  tuple("Plane", "Ocean", "Seaplane", "✈️", "A plane able to use ocean water is a seaplane."),
  tuple("Plane", "Fire", "Jet", "✈️", "Hot exhaust propelling a plane creates a jet."),
  tuple("Plane", "Space", "Spaceplane", "🚀", "A plane designed to enter space is a spaceplane."),
  tuple("Jet", "Ocean", "Aircraft Carrier", "🛳️", "Jets operating at sea use an aircraft carrier."),
  tuple("Rocket", "Ocean", "Splashdown", "🌊", "A returning rocket landing in the ocean makes a splashdown."),
  tuple("Rocket", "Planet", "Lander", "🚀", "A rocket vehicle built to reach a planet is a lander."),
  tuple("Rocket", "Space", "Spacecraft", "🚀", "A rocket traveling through space becomes a spacecraft."),
  tuple("Rocket", "Star", "Starship", "🚀", "A rocket imagined for interstellar travel becomes a starship."),
  tuple("Rocket", "Telescope", "Space Telescope", "🔭", "A telescope launched by rocket becomes a space telescope."),
  tuple("Spacecraft", "Planet", "Orbiter", "🛰️", "A spacecraft circling a planet is an orbiter."),
  tuple("Spacecraft", "Ocean", "Capsule", "🛸", "A spacecraft returning to the ocean lands in a capsule."),
  tuple("Spacecraft", "Space Station", "Docking", "🛰️", "A spacecraft meeting a space station performs docking."),
  tuple("Space Station", "Astronomy", "Space Observatory", "🔭", "Astronomy from a space station creates an orbital observatory."),
  tuple("Space Station", "Plant", "Space Garden", "🌱", "Plants cultivated aboard a station form a space garden."),
  tuple("Space", "Light", "Starlight", "⭐", "Light crossing deep space is starlight."),
  tuple("Space", "Dust", "Cosmic Dust", "✨", "Fine particles drifting through space are cosmic dust."),
  tuple("Space", "Ice", "Comet", "☄️", "A body of ice traveling through space is a comet."),
  tuple("Space", "Stone", "Asteroid", "☄️", "A rocky body traveling through space is an asteroid."),
  tuple("Space", "Metal", "Satellite", "🛰️", "A metal machine placed in space becomes a satellite."),
  tuple("Space", "Machine", "Probe", "🛰️", "A machine sent through space becomes a probe."),
  tuple("Planet", "Dust", "Planetary Ring", "🪐", "Dust orbiting a planet forms a planetary ring."),
  tuple("Planet", "Ice", "Ice Planet", "🪐", "A planet dominated by frozen material is an ice planet."),
  tuple("Planet", "Forest", "Living Planet", "🌍", "A planet covered in forests becomes a living planet."),
  tuple("Planet", "City", "Civilization", "🏛️", "Cities spread across a planet form a civilization."),
  tuple("Planet", "Sun", "Orbit", "🪐", "A planet follows an orbit around its sun."),
  tuple("Planet", "Star", "Exoplanet", "🪐", "A planet around another star is an exoplanet."),
  tuple("Star", "Dust", "Nebula", "🌌", "Starlight within interstellar dust reveals a nebula."),
  tuple("Star", "Comet", "Meteor Shower", "☄️", "Comet debris crossing starlight creates a meteor shower."),
  tuple("Star", "Hydrogen", "Fusion", "⚛️", "Hydrogen compressed in a star undergoes fusion."),
  tuple("Star", "Galaxy", "Cosmos", "🌌", "Stars across a galaxy evoke the wider cosmos."),
  tuple("Star", "Light", "Starlight", "⭐", "Light emitted by a star is starlight."),
  tuple("Galaxy", "Galaxy", "Universe", "🌌", "Galaxies together fill the observable universe."),
  tuple("Galaxy", "Telescope", "Deep Field", "🔭", "A telescope staring into a galaxy field creates a deep field."),
  tuple("Galaxy", "Planet", "Exoplanet", "🪐", "A planet identified in a distant galaxy is an exoplanet."),
  tuple("Galaxy", "Space", "Cosmos", "🌌", "Galaxies spread through space define the cosmos."),
  tuple("Constellation", "Telescope", "Stargazing", "🔭", "Viewing constellations through a telescope is stargazing."),
  tuple("Constellation", "City", "Light Pollution", "🌃", "City light can hide a constellation through light pollution."),
  tuple("Telescope", "Planet", "Planetary Science", "🔭", "Studying planets through telescopes supports planetary science."),
  tuple("Telescope", "Ocean", "Horizon", "🌅", "A telescope aimed across the ocean studies the horizon."),
  tuple("Telescope", "Glass", "Lens", "🔍", "A telescope's shaped glass is a lens."),
  tuple("Observatory", "City", "Planetarium", "🌌", "A public city observatory evokes a planetarium."),
  tuple("Observatory", "Mountain", "Clear Skies", "🌌", "A mountain observatory seeks clear skies."),
  tuple("Observatory", "School", "Science Center", "🔬", "An educational observatory becomes a science center."),
  tuple("School", "Tree", "Book", "📖", "Tree pulp made for school becomes a book."),
  tuple("Book", "Astronomy", "Star Atlas", "📖", "An astronomy book mapping stars is a star atlas."),
  tuple("Book", "School", "Library", "📚", "Books gathered for a school form a library."),
  tuple("Book", "Light", "Reading", "📖", "Light on a book makes reading possible."),
  tuple("Book", "Forest", "Field Guide", "📗", "A book for identifying forest life is a field guide."),
  tuple("Book", "City", "Directory", "📒", "A book listing city places becomes a directory."),
  tuple("Book", "Life", "Biography", "📖", "A book recording a life is a biography."),
  tuple("Astronomy", "School", "Science", "🔬", "Astronomy taught at school is science."),
  tuple("Science", "Life", "Biology", "🧬", "Science studying life is biology."),
  tuple("Science", "Space", "Astrophysics", "🌌", "Science applying physics to space is astrophysics."),
  tuple("Science", "Energy", "Physics", "⚛️", "Science studying energy and matter is physics."),
  tuple("Science", "Plant", "Botany", "🌿", "Science studying plants is botany."),
  tuple("Science", "Animal", "Zoology", "🐾", "Science studying animals is zoology."),
  tuple("Science", "Weather", "Meteorology", "🌦️", "Science studying weather is meteorology."),
  tuple("Science", "Ocean", "Oceanography", "🌊", "Science studying oceans is oceanography."),
  tuple("Science", "Star", "Astronomy", "🔭", "Science studying stars is astronomy."),
  tuple("Science", "Machine", "Engineering", "⚙️", "Applying science to machines becomes engineering."),
  tuple("Science", "Glass", "Microscope", "🔬", "Scientific glass lenses form a microscope."),
  tuple("Microscope", "Life", "Cell", "🧫", "A microscope reveals the cell as a unit of life."),
  tuple("Cell", "Cell", "Tissue", "🧫", "Similar cells working together form tissue."),
  tuple("Tissue", "Tissue", "Organ", "🫀", "Tissues working together form an organ."),
  tuple("Organ", "Organ", "Organism", "🧍", "Cooperating organs form an organism."),
  tuple("Organism", "Species", "Population", "👥", "Organisms of one species form a population."),
  tuple("Population", "City", "Census", "📊", "Counting a city's population produces a census."),
  tuple("School", "Science", "Laboratory", "🧪", "A school room for science becomes a laboratory."),

  // Intuitive identical-word upgrades and network effects.
  tuple("Road", "Road", "Highway", "🛣️", "Roads joined into a major route become a highway."),
  tuple("Street", "Street", "Avenue", "🏙️", "Connected broad streets form an avenue."),
  tuple("Bridge", "Bridge", "Viaduct", "🌉", "A long sequence of bridge spans forms a viaduct."),
  tuple("Train", "Train", "Rail Network", "🚆", "Many coordinated trains require a rail network."),
  tuple("Car", "Car", "Traffic Jam", "🚗", "Too many cars together create a traffic jam."),
  tuple("Boat", "Boat", "Marina", "⛵", "Boats gathered at sheltered docks form a marina."),
  tuple("Aircraft", "Aircraft", "Air Fleet", "✈️", "Aircraft operating together form an air fleet."),
  tuple("Library", "Library", "Library System", "📚", "Connected libraries together form a library system."),
  tuple("Paper", "Paper", "Ream", "📄", "Sheets of paper stacked together form a ream."),
  tuple("Log", "Log", "Log Cabin", "🛖", "Logs stacked and joined become a log cabin."),
  tuple("Cabin", "Cabin", "Village", "🏘️", "Cabins clustered together form a village."),
  tuple("Pet", "Pet", "Menagerie", "🐾", "Many different pets together form a menagerie."),
  tuple("Bee", "Bee", "Hive", "🐝", "Bees living together build a hive."),
  tuple("Flowerbed", "Flowerbed", "Garden", "🌷", "Several flowerbeds together form a garden."),
  tuple("Cactus", "Cactus", "Desert Garden", "🌵", "A collection of cacti forms a desert garden."),
  tuple("Island", "Island", "Archipelago", "🏝️", "A chain of islands forms an archipelago."),
  tuple("Coast", "Coast", "Shoreline", "🏖️", "Connected stretches of coast form a shoreline."),
  tuple("Wave", "Wave", "Surf", "🏄", "Breaking waves together create surf."),
  tuple("Waterfall", "Waterfall", "Rapids", "💦", "Repeated drops and churning water become rapids."),
  tuple("Canyon", "Canyon", "Badlands", "🏜️", "A maze of eroded canyons forms badlands."),
  tuple("Mesa", "Mesa", "Plateau", "🏜️", "Broad joined mesas form a plateau."),
  tuple("Wetland", "Wetland", "Marsh", "🪷", "Connected wetlands spread into marshland."),
  tuple("Habitat", "Habitat", "Biome", "🌍", "Related habitats across a region form a biome."),
  tuple("Population", "Population", "Society", "👥", "Populations interacting together form a society."),
  tuple("Neighborhood", "Neighborhood", "Borough", "🏙️", "Neighborhoods grouped administratively form a borough."),
  tuple("Apartment", "Apartment", "Apartment Block", "🏢", "Many apartments together form an apartment block."),
  tuple("Skyscraper", "Skyscraper", "Skyline", "🌆", "Skyscrapers together shape a city skyline."),
  tuple("Circuit", "Circuit", "Computer", "💻", "Many coordinated circuits form a computer."),
  tuple("Computer", "Computer", "Network", "🖧", "Computers connected together form a network."),
  tuple("Network", "Network", "Internet", "🌐", "Networks linked worldwide form the internet."),
  tuple("Satellite", "Satellite", "Satellite Constellation", "🛰️", "Coordinated satellites form a satellite constellation."),
  tuple("Asteroid", "Asteroid", "Asteroid Belt", "☄️", "Many asteroids sharing an orbit form an asteroid belt."),
  tuple("Nebula", "Nebula", "Star Nursery", "🌌", "Dense nebulae become stellar nurseries."),
  tuple("Exoplanet", "Exoplanet", "Planetary System", "🪐", "Multiple exoplanets around a star form a planetary system."),
  tuple("Tissue", "Organ", "Anatomy", "🫀", "Tissues and organs together define anatomy."),
  tuple("Book", "Science", "Textbook", "📘", "A book organized to teach science becomes a textbook."),
  tuple("Textbook", "Textbook", "Encyclopedia", "📚", "Many comprehensive textbooks evoke an encyclopedia."),
  tuple("Notebook", "Notebook", "Archive", "🗄️", "Stored notebooks together form an archive."),
  tuple("Trail", "Trail", "Trail System", "🥾", "Connected trails form a trail system."),
  tuple("Greenhouse", "Greenhouse", "Botanical Garden", "🌿", "Many greenhouses together support a botanical garden."),
  tuple("Factory", "Factory", "Industrial Complex", "🏭", "Factories grouped together form an industrial complex."),
  tuple("Airport", "Airport", "Air Network", "✈️", "Connected airports form an air travel network."),
  tuple("Harbor", "Harbor", "Port", "⚓", "Several working harbors form a major port."),
  tuple("Reservoir", "Reservoir", "Waterworks", "🚰", "Linked reservoirs and pipes form waterworks."),
  tuple("Turbine", "Turbine", "Wind Farm", "🌬️", "Many wind turbines together form a wind farm."),
  tuple("Motor", "Motor", "Engine", "⚙️", "Coordinated motors form a larger engine system."),
  tuple("Lens", "Lens", "Binoculars", "🔭", "Two matched lenses form binoculars."),
  tuple("Microscope", "Microscope", "Laboratory", "🧪", "Multiple microscopes belong in a laboratory."),
  tuple("Room", "Room", "House", "🏠", "Connected rooms together form a house."),
  tuple("Furniture", "Furniture", "Furnishings", "🪑", "Furniture collected for a room becomes furnishings."),
  tuple("Plate", "Plate", "Dinnerware", "🍽️", "Plates gathered as a set become dinnerware."),
  tuple("Bread", "Bread", "Sandwich", "🥪", "Two slices of bread make the basis of a sandwich."),
  tuple("Tea", "Tea", "Tea Party", "🫖", "Tea shared in company becomes a tea party."),
  tuple("Fruit", "Fruit", "Fruit Salad", "🍓", "Different fruits mixed together make fruit salad."),
  tuple("Grain", "Grain", "Cereal", "🥣", "Prepared grains together become cereal."),
  ...worldGraphLegacyRecipes().map((recipe) => Object.freeze(recipe)),
  ...GRAPH_BREADTH_RECIPES
]);

export function expandedRecipeKey(a, b) {
  return [a, b].map((value) => String(value || "").trim().toLowerCase()).sort().join("+");
}

const wordPattern = /^[\p{L}\p{N}][\p{L}\p{N} '&-]*$/u;

export function validateExpandedRecipes(recipes = EXPANDED_RECIPES, { baseConcepts = EXPANDED_RECIPE_BASE_CONCEPTS } = {}) {
  const issues = [];
  const known = new Set([...baseConcepts].map((word) => String(word).trim().toLowerCase()).filter(Boolean));
  const pairs = new Set();
  const outputCounts = new Map();
  let reachable = 0;

  for (let index = 0; index < recipes.length; index += 1) {
    const recipe = recipes[index];
    const label = `recipe ${index + 1}`;
    if (!recipe || typeof recipe !== "object") {
      issues.push(`${label} is not an object.`);
      continue;
    }
    const a = String(recipe.a || "").trim();
    const b = String(recipe.b || "").trim();
    const word = String(recipe.word || "").trim();
    const note = String(recipe.note || "").trim();
    const emoji = String(recipe.emoji || "").trim();
    const key = expandedRecipeKey(a, b);
    const ingredientsReachable = known.has(a.toLowerCase()) && known.has(b.toLowerCase());
    if (!a || !b) issues.push(`${label} has a missing ingredient.`);
    if (pairs.has(key)) issues.push(`${label} duplicates unordered pair ${a} + ${b}.`);
    pairs.add(key);
    if (!known.has(a.toLowerCase())) issues.push(`${label} uses ${a} before it is reachable.`);
    if (!known.has(b.toLowerCase())) issues.push(`${label} uses ${b} before it is reachable.`);
    if (!wordPattern.test(word) || word.length > 32) issues.push(`${label} has an invalid result word.`);
    if ([a, b].some((input) => input.toLowerCase() === word.toLowerCase())) issues.push(`${label} returns an input unchanged.`);
    if (!emoji || emoji.length > 16) issues.push(`${label} has an invalid emoji.`);
    if (!note || note.length > 120) issues.push(`${label} has an invalid explanation.`);
    const compact = word.toLowerCase().replace(/[^a-z]/g, "");
    if (/(.{2,10})\1\1/i.test(compact) || /(craft){2,}/i.test(compact)) issues.push(`${label} resembles generated nonsense.`);
    outputCounts.set(word.toLowerCase(), (outputCounts.get(word.toLowerCase()) || 0) + 1);
    if (ingredientsReachable) {
      known.add(word.toLowerCase());
      reachable += 1;
    }
  }

  const concentrations = [...outputCounts.entries()]
    .map(([word, count]) => ({ word, count }))
    .sort((left, right) => right.count - left.count || left.word.localeCompare(right.word));
  const maximumResultConcentration = concentrations[0]?.count || 0;
  if (maximumResultConcentration > 4) issues.push(`Result concentration exceeds four for ${concentrations[0].word}.`);

  return {
    valid: issues.length === 0,
    issues,
    report: {
      schemaVersion: 1,
      recipeCount: recipes.length,
      uniquePairCount: pairs.size,
      reachableRecipeCount: reachable,
      distinctResultCount: outputCounts.size,
      maximumResultConcentration,
      topResultConcentrations: concentrations.slice(0, 12)
    }
  };
}

export function expandedRecipeReport(recipes = EXPANDED_RECIPES, options) {
  return structuredClone(validateExpandedRecipes(recipes, options).report);
}

export const EXPANDED_LOGICAL_SPOT_CHECKS = Object.freeze([
  ["Rain", "Sun", "Sunshower"], ["Fog", "Light", "Halo"], ["River", "Ocean", "Estuary"],
  ["Mountain", "River", "Waterfall"], ["Ocean", "Volcano", "Island"], ["Desert", "Plant", "Cactus"],
  ["Forest", "Fog", "Cloud Forest"], ["Swamp", "Tree", "Mangrove"], ["River", "Stone", "Canyon"],
  ["Mud", "River", "Delta"], ["Cloud", "Sun", "Silver Lining"], ["Atmosphere", "Planet", "Climate"],
  ["Plant", "Sun", "Photosynthesis"], ["Axe", "Tree", "Log"], ["Log", "Water", "Raft"],
  ["Seed", "Rain", "Seedling"], ["Leaf", "Water", "Dew"], ["Farm", "Machine", "Tractor"],
  ["Field", "Animal", "Pasture"], ["Ecosystem", "Species", "Biodiversity"], ["Animal", "House", "Pet"],
  ["Bird", "Tree", "Nest"], ["Fish", "River", "Trout"], ["Tree", "Flower", "Fruit"],
  ["Grain", "Fire", "Bread"], ["Bee", "Flower", "Honey"], ["Clay", "House", "Adobe"],
  ["Stone", "Wall", "Rampart"], ["Megacity", "River", "Bridge"], ["Land", "City", "Road"],
  ["Road", "Machine", "Vehicle"], ["Raft", "Metal", "Boat"], ["Metal", "Road", "Railway"],
  ["Railway", "Machine", "Train"], ["Dam", "River", "Reservoir"], ["Steel", "Machine", "Robot"],
  ["Lumber", "Water", "Paper Pulp"], ["Paper", "School", "Notebook"], ["Electricity", "Metal", "Circuit"],
  ["Electricity", "Glass", "Light Bulb"], ["Engine", "Train", "Locomotive"], ["Plane", "City", "Airport"],
  ["Rocket", "Planet", "Lander"], ["Space", "Stone", "Asteroid"], ["Planet", "Star", "Exoplanet"],
  ["Star", "Hydrogen", "Fusion"], ["School", "Tree", "Book"], ["Science", "Life", "Biology"],
  ["Science", "Glass", "Microscope"], ["Cell", "Cell", "Tissue"], ["Road", "Road", "Highway"],
  ["Island", "Island", "Archipelago"], ["Circuit", "Circuit", "Computer"], ["Computer", "Computer", "Network"],
  ["Network", "Network", "Internet"], ["Bread", "Bread", "Sandwich"]
].map(([a, b, word]) => Object.freeze({ a, b, word })));
